### ISSUE TITLE
Architectural review

### ISSUE THREAD

**Issue by kirkbushell** [Yord/warfaster#2]
So, I'll leave the UI stuff out for now, as you have already mentioned that until you have everything in place, you'll leave it as one file - all good.

1. I think the support of a drag-drop feature for an app that would be mostly used by mobile is potentially a bit of feature-creep/overreach. Ie. Although nice, probably not all that useful, particularly if you add a sorting mechanism. Also, my testing has shown that this is problematic/buggy on both desktop and mobile devices, resulting in very bizarre UX outcomes (I went to scroll on mobile with a unit "open", and it tried to drag-drop the element, which it then immediately dropped).
2. The cache system needs a rethink just in terms of *when* it runs, not *how* it runs. Running on app load or refresh is not all that great, but could perhaps simply require a better UX. Ie. Loading app data... along with a loader % (which could be done based on the # of pages it needs to query and cache). That way, if it's a 20 second load time, who cares - it's clear on the UI what is left. On subsequent loads, this could be done in the background (if it's not already).
3. I would strongly recommend moving away from vanilla css to something like tailwind. It'll also ensure you can avoid the strange media query checks you're doing on <Col component calls. This becomes an even more valuable move once you start splitting your components up like you should be :P
4. I notice on desktop with multiple lists it lists them horizontally - does this become an infinite horizontal scrollbar? I refer back to my original issue #1 that showing lists in this manner is not a great UX, so might be something to think over.
5. Looking at how some things are rendered... it seems rather verbose. I think this is in part due to the linter which is splitting HTML fragments and their attributes onto separate lines, making it rather ugly and difficult to read and follow. This may be resolved in part due to having UI components separated properly, but I'm not so sure. For example:

```jsx
<span className="subtitle">
  {[
    ...(!details ||
    !details.vehicleWeaponSelection ||
    !vehicleWeaponName(
      details.vehicleWeaponSelection,
      vehicleWeaponId
    )
      ? []
      : [
          vehicleWeaponName(
            details.vehicleWeaponSelection,
            vehicleWeaponId
          ),
        ]),
    ...(!details ||
    !details.cortexSelections ||
    !cortexName(
      details.cortexSelections,
      cortexIds
    )
      ? []
      : [
          cortexName(
            details.cortexSelections,
            cortexIds
          ),
        ]),
    ...(!details ||
    !details.warjackWeaponSelections ||
    !warjackWeaponIds ||
    warjackWeaponIds.length ===
      0
      ? []
      : warjackWeaponNamesSubtitle(
          details.warjackWeaponSelections,
          warjackWeaponIds
        )),
  ].join(", ")}
</span>
</div>
```

Yikes!!!

I would recommend leaving state checks to the objects you're working with (also you can invert this logic check to simply check for object validity first): Ie.

```javascript
if (details && details.hasSelections())
```

I'll leave it there for now.

**Comment by Yord** [comment]
@kirkbushell Thanks for your thorough review!

1.  I agree. The drag-and-drop feature was a nice idea, but it has never really worked seamlessly for me either and it is really a source of some puzzling bugs. I am not sure, to be honest, how to implement moving cards in a better way though, which is why I have not touched it even after the bugs were obvious.
2.  I love the idea of a loading bar. This is a superior solution to what's in the app now.
3.  Yes totally agree on that part. The CSS is a mess at the moment, including stuff that is probably not being used anymore at the moment. I feel like it is almost too late to save it 😅. But yeah, when breaking up the UI into components, the CSS should also be broken up and become component local.
4.  Nah it does not become an infinite scrollbar 😉. Depending on device width, I display 2/3/4 lists horizontally and break all further lists vertically. The motivation was that it just looked very silly in a desktop browser if you had just a single list with a width of 1000+px. I am personally using the builder more from a laptop than from a smartphone and having more lists side-by-side is actually quite nice. Also, since you usually only have two lists anyway, maybe three, it usually does not break vertically.
5.  Yeah the formatting is due to the linter. However, obviously, it is also due to the fact that you should just not put so much stuff in one line of code. I feel kind of bad about it, but was pragmatic and told myself to fix it once the file is broken into smaller modules.
    I agree with your remark on state checks 👍.

**Comment by kirkbushell** [comment]
1. I wouldn't bother about moving cards. Order them by type (solo, squad, jack.etc.) and then alphabetically by that. End users will get used to the order (I'd definitely start with solos/heroes at the top, as these tend to define lists).
2. Happy to work on this once we get going :)
3. It's never too late. Honestly I think I could address this pretty easily for you. Not sure if you've ever worked with tailwind but once you "get" its workflow, my god it's a fast way to work. Wouldn't want to do this until starting to refactor, though. Tailwind plays nicely into well-structured applications and component re-use.
5. Ah, I see. Could use flex here with flex-wrap enabled, but I think a UI that supports first adding/selecting lists and then modifying them might be better. hehe
6. Haha, agreed.

**Comment by Yord** [comment]
The points raised in this issue have seen some work since it was raised. I would like to summarize what has happened and then close the issue:

1. Drag-and-drop has been replaced with a button (up/down) based approach to moving cards as well as lists. The up/down buttons are only available in "edit mode" and otherwise hidden in the UI. I did not add sorting, but I have it on my todo list with low priority and may or may not approach it later depending on when I will stop adding more features.
2. I did not add a loading bar, but I did revamp the loading screen. The loading bar is hard to realize, since I cannot say at the time of loading the app, how many pages I have to load. Since the loading time is `number_of_pages * 2 seconds`, and one cannot know `number_of_pages` in advance, a percentage-based loading bar cannot be implemented.
3. CSS is still a mess and will probably remain one tbh. Should have started out differently from the beginning I guess. But then again, this was never a focus and was this neglected.
4. I do use flex in some areas but mostly fall back on whatever ant-design uses. This remains unchanged from when this was reported.
5. I started refactoring commits that clean up the App component. I am not done yet, but the code already is much more untangled and will continue to be cleaned up.
