### ISSUE TITLE
Data loading improvement

### ISSUE THREAD

**Issue by kirkbushell** [Yord/warfaster#3]
As mentioned in #1 and #2, loading of data for initial app load is clumsy. It doesn't communicate what is going on and so this leaves the end user in a bit of a confused state.

We can speed up load times significantly by reducing the limit on page loads (1 every 2 seconds) to several per second, and then show a loader that communicates how much is left to load. This is currently cached once loaded, so great.

After this, regular background checks (perhaps setting a timeout to run every day or week), and then this just syncs the data in the background.

**Comment by Yord** [comment]
A lot has happened since this issue was reported. Let me summarize it:

I will for now stick with a single page load every two seconds to play nice in terms of crawling. That means the very first time the web app is loaded will remain slow. All subsequent accesses will be faster.

I do have a pre-caching and shipping of data on my to-do list. But it has a very low priority and it may very well not make the cut.

Background checks are implemented and run on every page reload.
