### ISSUE TITLE
Add on-the-fly list validation

### ISSUE THREAD

**Issue by kirkbushell** [Yord/warfaster#5]
List validation is quite important to accurate list construction, and the limitations and rules so far are relatively minor:

1. Select battle size (skirmish.etc.)
2. Add units, ensuring not to eclipse battle size limits (such as 8 units + 1 hero for skirmishes)
3. Any units that break the rules when changes are made, are highlighted red and potentially at half opacity to show that they're no longer valid. This could happen probably most likely when changing battle size.

**Comment by Yord** [comment]
I have decided not to have list validation in the app. The decision is for pragmatic reasons: When the validation changes, it would need to be updated. And I cannot guarantee, that I will be able to do that fast. So rather than having out-of-date or wrong validation, I rather not validate at all.

Also, there are already more than the two official battle sizes with Arcane Synthesis' community mode and my own Hidden agendas mode. I am sure there are more modes, that I am not aware of. So, again, rather than risking to not support a mode that people want to play, I rather not restrict list creation.

**Comment by kirkbushell** [comment]
You can achieve both if you want to be truly pragmatic - add validation, and add the option to disable it by the end user ;)

**Comment by Yord** [comment]
That does not prevent outdated or wrong validation. The end user would have to know that it is outdated or wrong to disable it.

**Comment by kirkbushell** [comment]
Might be misunderstanding the suggestion. I do exactly that on fabdb.net. Players create decks, and can turn off validation so that they can add whatever they want via an "Open" deck format. Else validation applies.

**Comment by Yord** [comment]
This is a good idea in general. However, let's assume the following hypothetical scenario:

It is November 2020 when Warfaster's validation rules are last changed. It now has "Collision Course" validation rules. In Juli 2021 with the release of "The Thousand Worlds" the game's validation rules change with the introduction of champion models. But at this point, Warfaster is not being maintained anymore and the validation rules are not updated.

Champion models are being added to PP's wiki and are thus automatically available in Warfaster, although it is not being maintained anymore. The validation rules now force you to pay a list slot for champion models, although unnecessary. But users have learned to trust Warfaster's validation rules and do not question them.

In this situation, the validation rules Warfaster enforces are outdated and always wrong and users may not know it. So the initial benefit of enforcing them by default has become a hindrance instead, that will never be fixed because Warfaster is not being maintained anymore.

I am building Warfaster with the very real possibility in mind, that I will stop maintaining it at some point. This is why its contents are fully dependent on PP's wiki, with the hope, that it will be continued to be maintained and fixes and new factions and models will continue to be added to Warfaster automatically. So I am hesitant to hardcode anything in Warfaster that may be outdated at some point. And validation rules are still in flux and are an example of rules that have already been updated in the past.
